import Image from "next/image";

const Circles = () => {
  return (
    <div className="mt-14 select-none hidden sm:flex gap-1">
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_10s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_5s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_1s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_15s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_4s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_7s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_3s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_13s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_6s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_10s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_5s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_11s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_3s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_13s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_1s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_15s_linear_infinite]"
      />
      <Image
        alt="circle"
        quality="100"
        width={24.29}
        height={24.29}
        layout="fixed"
        src="/circle.png"
        className="animate-[spin_7s_linear_infinite]"
      />
    </div>
  );
};

export default Circles;
